# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inventory.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finventory.proto\x12\tinventory\";\n\x11\x41\x64\x64ProductRequest\x12\x14\n\x0cproduct_name\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\"6\n\x12\x41\x64\x64ProductResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2]\n\x10InventoryService\x12I\n\nAddProduct\x12\x1c.inventory.AddProductRequest\x1a\x1d.inventory.AddProductResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inventory_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ADDPRODUCTREQUEST._serialized_start=30
  _ADDPRODUCTREQUEST._serialized_end=89
  _ADDPRODUCTRESPONSE._serialized_start=91
  _ADDPRODUCTRESPONSE._serialized_end=145
  _INVENTORYSERVICE._serialized_start=147
  _INVENTORYSERVICE._serialized_end=240
# @@protoc_insertion_point(module_scope)
