# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cserver.proto\x12\tinventory\"\x07\n\x05\x45mpty\"1\n\x07Product\x12\x14\n\x0cproduct_name\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\"3\n\x0bProductList\x12$\n\x08products\x18\x01 \x03(\x0b\x32\x12.inventory.Product2\x88\x01\n\x10InventoryService\x12\x39\n\x0bGetProducts\x12\x10.inventory.Empty\x1a\x16.inventory.ProductList\"\x00\x12\x39\n\x0b\x41\x64\x64Products\x12\x16.inventory.ProductList\x1a\x10.inventory.Empty\"\x00\x32\x86\x01\n\x0e\x43\x61talogService\x12\x39\n\x0b\x41\x64\x64Products\x12\x16.inventory.ProductList\x1a\x10.inventory.Empty\"\x00\x12\x39\n\x0bGetProducts\x12\x10.inventory.Empty\x1a\x16.inventory.ProductList\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'server_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMPTY._serialized_start=27
  _EMPTY._serialized_end=34
  _PRODUCT._serialized_start=36
  _PRODUCT._serialized_end=85
  _PRODUCTLIST._serialized_start=87
  _PRODUCTLIST._serialized_end=138
  _INVENTORYSERVICE._serialized_start=141
  _INVENTORYSERVICE._serialized_end=277
  _CATALOGSERVICE._serialized_start=280
  _CATALOGSERVICE._serialized_end=414
# @@protoc_insertion_point(module_scope)
